# This file is documented at `src/config.rs`. Look there if you're looking to tweak it.

# clib, sysclib, kernel/debug all use va_list.
[[lists]]
files = [
    "psp2/kernel/clib.h",
    "psp2kern/kernel/sysclib.h",
    "psp2kern/kernel/debug.h",
    "psp2/paf/stdc.h"
]
allowlists = ["va_list"]

# rtc uses time_t.
[[lists]]
files = ["psp2/rtc.h"]
allowlists = ["time_t"]

# SceIoDevInfo is actually defined in psp2common/kernel/iofilemgr.h, but it's
# included via transitive dependency only (psp2/io/devctl.h)
# TODO: way to add include / use statement?
[[lists]]
files = ["psp2/compat.h"]
allowlists = ["SceIoDevInfo"]
